### ISSUE TITLE
DOCTYPE not supported in Microsoft EDGE

### ISSUE THREAD

**Issue by rjpaulsen** [t-davies/magicxml#8]
When I have this in my XSLT:

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE xsl:stylesheet [
  <!ENTITY nbsp "<xsl:text disable-output-escaping='yes'>&amp;nbsp;</xsl:text>">
]>

```

It works in Chrome. But when I use Microsoft Edge, I get:

> No such interface supported

**Comment by t-davies** [comment]
Hey, sorry for such a delay. Going to start maintaining this a bit more now. Is this still an issue? I can see a bug report against Edge for something similar has now been fixed (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5552211/).
